### ISSUE TITLE
Broken references, no longer able to load any projects from platforms folder in gamestatemanagement

### ISSUE THREAD

**Issue by IDEDOnline** [SimonDarksideJ/MonoGameSamples#1]
Unfortunately this set of samples is no longer usable, the references are not packaged with the solution even if you download all the folders referenced manually and rebuild it seems that MonoGame\v3.0\MonoGame.Content.Builder.targets prevents loading all projects within the solution beyond the core making it unusable to learn from.

**Comment by SimonDarksideJ** [comment]
Updated the checkout for the GSM sample to the latest 3.8 branch, which is fully working
